repos:
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    name: Black format python files
    language_version: python3 # Should be a command that runs python3.6+
    entry: black --line-length 119

- repo: https://gitlab.com/pycqa/flake8
  rev: '3.8.3'  # pick a git hash / tag to point to
  hooks:
  - id: flake8
    additional_dependencies: [flake8-deprecated, flake8-debugger, flake8-bugbear]

- repo: https://github.com/timothycrosley/isort
  rev: 5.4.2
  hooks:
  - id: isort
    entry: isort --check-only --use-parentheses --trailing-comma --line-length 119
    language_version: python3
